# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tES4aslLKfuhuLM9V44Q0-lZdNkbrE67
"""

!pip install gradio transformers accelerate torch

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

class ColorPaletteGenerator:

    palettes = {
        "modern": {
            "primary": "#6366f1",
            "secondary": "#8b5cf6",
            "background": "#0f172a",
            "text": "#ffffff"
        },
        "minimal": {
            "primary": "#000000",
            "secondary": "#444444",
            "background": "#ffffff",
            "text": "#000000"
        },
        "dark": {
            "primary": "#1f2937",
            "secondary": "#374151",
            "background": "#111827",
            "text": "#f9fafb"
        },
        "pastel": {
            "primary": "#f472b6",
            "secondary": "#60a5fa",
            "background": "#fdf2f8",
            "text": "#1f2937"
        },
        "nature": {
            "primary": "#16a34a",
            "secondary": "#15803d",
            "background": "#f0fdf4",
            "text": "#14532d"
        },
        "corporate": {
            "primary": "#1d4ed8",
            "secondary": "#1e40af",
            "background": "#f8fafc",
            "text": "#0f172a"
        },
        "sunset": {
            "primary": "#f97316",
            "secondary": "#ea580c",
            "background": "#fff7ed",
            "text": "#7c2d12"
        },
        "luxury": {
            "primary": "#d4af37",
            "secondary": "#b8860b",
            "background": "#000000",
            "text": "#ffffff"
        }
    }

    @staticmethod
    def get_palette(style):
        return ColorPaletteGenerator.palettes.get(style, ColorPaletteGenerator.palettes["modern"])

class HTMLPageBuilder:

    def __init__(self, title, description, palette):
        self.title = title
        self.description = description.lower()
        self.palette = palette

    def section(self, title, content):
        return f"""
        <section style="padding:60px; text-align:center;">
            <h2 style="color:{self.palette['primary']}">{title}</h2>
            <p>{content}</p>
        </section>
        """

    def build_contact(self):
        return f"""
        <section style="padding:60px; text-align:center;">
            <h2 style="color:{self.palette['primary']}">Contact Us</h2>
            <input placeholder="Your Name"><br><br>
            <input placeholder="Your Email"><br><br>
            <textarea placeholder="Message"></textarea><br><br>
            <button style="background:{self.palette['primary']};
            color:white;padding:10px 20px;border:none;">
                Send Message
            </button>
        </section>
        """

    def generate_page(self):

        html = f"""
        <html>
        <head>
        <title>{self.title}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
        body {{
            background:{self.palette['background']};
            color:{self.palette['text']};
            font-family:Arial;
            margin:0;
        }}
        header {{
            background:{self.palette['primary']};
            padding:20px;
            text-align:center;
            color:white;
        }}
        footer {{
            background:{self.palette['secondary']};
            padding:20px;
            text-align:center;
            color:white;
        }}
        </style>
        </head>
        <body>

        <header>
            <h1>{self.title}</h1>
        </header>
        """

        if "hero" in self.description:
            html += self.section("Welcome", "This is a modern AI generated website.")

        if "features" in self.description:
            html += self.section("Features", "Amazing features of our service.")

        if "about" in self.description:
            html += self.section("About Us", "We are professionals delivering quality.")

        if "portfolio" in self.description:
            html += self.section("Portfolio", "Our recent works and projects.")

        if "testimonials" in self.description:
            html += self.section("Testimonials", "What our clients say about us.")

        if "contact" in self.description:
            html += self.build_contact()

        if "footer" in self.description:
            html += """
            <footer>
                <p>© 2026 All Rights Reserved</p>
            </footer>
            """

        html += "</body></html>"
        return html

from typing import Dict

class HTMLQuickStyler:

    @staticmethod
    def generate_css(palette: Dict) -> str:
        css = f"""
        <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        :root {{
            --primary: {palette['primary']};
            --secondary: {palette['secondary']};
            --accent: {palette['accent']};
            --background: {palette['background']};
            --surface: {palette['surface']};
            --text-primary: {palette['text_primary']};
            --text-secondary: {palette['text_secondary']};
            --border: {palette['border']};
        }}

        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: var(--background);
            color: var(--text-primary);
            padding: 20px;
        }}

        .container {{
            background-color: var(--surface);
            padding: 20px;
            border-radius: 10px;
            border: 1px solid var(--border);
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }}

        h1 {{
            color: var(--primary);
            margin-bottom: 10px;
        }}

        p {{
            color: var(--text-secondary);
            margin-bottom: 15px;
        }}

        button {{
            background-color: var(--primary);
            color: white;
            border: none;
            padding: 10px 15px;
            border-radius: 5px;
            cursor: pointer;
        }}

        button:hover {{
            background-color: var(--secondary);
        }}

        .card {{
            background-color: var(--background);
            padding: 15px;
            border-radius: 8px;
            border: 1px solid var(--border);
            margin-top: 15px;
        }} </style>
        """
        return css

import gradio as gr

def generate_page(title, description, style):
    palette = ColorPaletteGenerator.get_palette(style)
    builder = HTMLPageBuilder(title, description, palette)
    html = builder.generate_page()
    return html, html

with gr.Blocks(theme=gr.themes.Monochrome()) as demo:

    gr.Markdown("# 🚀 HTML Quick-Styler Advanced")
    gr.Markdown("Professional HTML Page Generator with Auto-Styling")

    with gr.Tabs():

        # ------------------------
        # TAB 1 - Generate Page
        # ------------------------
        with gr.Tab("Generate Page"):

            with gr.Row():

                # LEFT SIDE INPUT
                with gr.Column(scale=1):
                    title = gr.Textbox(label="Page Title")
                    description = gr.Textbox(label="Page Description & Sections")
                    style = gr.Dropdown(
                        ["modern","ocean","forest","sunset","luxury","creative","minimal","vibrant"],
                        label="Color Style"
                    )
                    btn = gr.Button("Generate HTML", variant="primary")

                # RIGHT SIDE OUTPUT CODE
                with gr.Column(scale=1):
                    output = gr.Code(label="Generated HTML", language="html")

        # ------------------------
        # TAB 2 - Live Preview
        # ------------------------
        with gr.Tab("Live Preview"):
            preview = gr.HTML()

        # ------------------------
        # TAB 3 - Color Palettes
        # ------------------------
        with gr.Tab("Color Palettes"):
            gr.Markdown("### Available Themes")
            gr.Markdown("modern | ocean | forest | sunset | luxury | creative | minimal | vibrant")

        # ------------------------
        # TAB 4 - Templates
        # ------------------------
        with gr.Tab("Templates"):
            gr.Markdown("### Quick Templates")
            gr.Markdown("Portfolio Website")
            gr.Markdown("SaaS Landing Page")
            gr.Markdown("Corporate Website")

        # ------------------------
        # TAB 5 - Guide
        # ------------------------
        with gr.Tab("Guide"):
            gr.Markdown("### How It Works")
            gr.Markdown("1. Enter Title")
            gr.Markdown("2. Describe Sections")
            gr.Markdown("3. Choose Color Style")
            gr.Markdown("4. Click Generate")

    btn.click(generate_page,
              inputs=[title, description, style],
              outputs=[output, preview])

demo.launch(share=True)